export const MYPAGE_DATA = {
  name: 'testdd',
  unitsList: [
    { id: 6, type: '문자와 식' },
    { id: 2, type: '정수와 유리수' },
    { id: 1, type: '자연수의 성질' },
    { id: 3, type: '유리수와 소수' },
    { id: 4, type: '유리수와 순환소수' },
    { id: 5, type: '실수와 제곱근' },
    { id: 7, type: '식의 계산' },
    { id: 8, type: '인수분해' },
    { id: 9, type: '일차방정식' },
    { id: 10, type: '좌표평면과 그래프' },
    { id: 11, type: '일차함수' },
    { id: 12, type: '연립방정식' },
    { id: 13, type: '이차방정식' },
    { id: 14, type: '이차함수' },
    { id: 15, type: '기본 도형' },
    { id: 16, type: '도형의 이동' },
    { id: 17, type: '도형의 성질' },
    { id: 18, type: '도형의 작도와 합동' },
    { id: 19, type: '삼각형과 사각형' },
    { id: 20, type: '피타고라스 정리' },
    { id: 21, type: '원의 방정식' },
    { id: 22, type: '자료의 수집과 정리' },
    { id: 23, type: '평균과 중앙값' },
    { id: 24, type: '가능성' },
    { id: 25, type: '자료의 표현과 해석' },
    { id: 26, type: '확률' },
    { id: 27, type: '통계의 이해와 활용' },
  ],
};
